version: '2'
services:
    microservicesgate-mariadb:
        container_name: microservicesgate-mariadb
        image: mariadb:10.1.17
        # volumes:
        #     - ~/volumes/jhipster/microservicesGate/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=microservicesgate
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
