version: '2'
services:
    microservices-app:
        image: microservices
        external_links:
            - microservices-mariadb:mariadb
            - microservices-elasticsearch:elasticsearch
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/microservices
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
    microservices-mariadb:
        extends:
            file: mariadb.yml
            service: microservices-mariadb
    microservices-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: microservices-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
